test/onigumo_test.exs

We do not have any test cases in our documentation strings. Thus `doctest` is not used and not needed. See [ExUnit.DocTest](https://hexdocs.pm/ex_unit/ExUnit.DocTest.html#doctest/2).

Remove unused doctest

---

config/config.exs
config/test.exs
test/onigumo_test.exs

* Use parentheses for function calls. That includes `import_config`,
`config`, `test`, `assert`, `setup` or `defmock`.
* Do not use parentheses for [Kernel](https://hexdocs.pm/elixir/Kernel.html) calls and [special forms](https://hexdocs.pm/elixir/Kernel.SpecialForms.html). That includes `def`,
`defp`, `defmodule`, `use` or `import`.
This makes the code consistent, yet avoiding strange syntax like `defmodule(…)`.
I am not sure what a good solution is. Maybe keeping asserts, test definitions and config calls without parentheses would be more readable. Yet I’d like to keep the number of exception as low as possible, sticking only to _Kernel_.

Consolidate parentheses in calls

---

config/dev.exs

In #20 we removed parentheses for [_Kernel.SpecialForms_](https://hexdocs.pm/elixir/Kernel.SpecialForms.html) like [`import`](https://hexdocs.pm/elixir/Kernel.SpecialForms.html#import/2). One import however remained unnoticed.

Remove parentheses from import

---

lib/onigumo.ex
test/onigumo_test.exs

The `http_client` argument is a configuration, `url` is an input. Keep
input values first to make it easier to use with `|>` piping.
```elixir
get_url() |> download(http_client)
```

Swap download/2 argument order

---

test/onigumo_test.exs

Use `@input_filename`and `@output_filename` in the test to be consistent with the executive code naming.

Unify attribute names

---

test/onigumo_test.exs

An HTTP response is a text file and every text file should end with a newline.

Add newline to the end of the response body

---

test/onigumo_test.exs

The "load URL from file" test contained an unwanted space in the URL list written to a file. The URLs are expected not to have any whitespace other than the newline.

Remove unwanted space from URL list

---

lib/onigumo.ex
test/onigumo_test.exs

This allows to use `tmp_dir` for `download/2` (now `/3`) tests.
Fixes #32 if not considering #29.

Parametrize output filename

---

lib/onigumo.ex

`Application.get_env(:onigumo, :http_client)` returns `HTTPoison` in dev environment. This value can be used to call `start` upon. Doing so the dichotomy between using literal `HTTPoison` for `start`, but the env one for `get!` would disappear.
Related to https://github.com/Glutexo/onigumo/pull/46.

Always use env HTTP client

---

test/onigumo_test.exs

Extracted the `load_urls/1` test for multiple URLs from #29 to make the changes more atomic. It reintroduces some necessary changes like switching from a single `@url` attribute to a multiple `@urls` list attribute. I kept the style of the existing tests, keeping possible refactoring to follow-up pull requests, most of which are already in place.

Test load multiple URLs

---

test/onigumo_test.exs

To avoid accidentally hitting a real world server in case of failed mocking.

Change test URL domain to local

---

lib/onigumo.ex
test/onigumo_test.exs

fix #26 
From @Glutexo: This required a slight change in the executive code so that the `download` function can accept a list of URLs without initializing the real environment application.

Test download of multiple URLs

---

lib/onigumo.ex

There is no need to have a separate http_client function that only simply wraps around `Application.get_env/3` called from a single place. In the tests we are mocking _HTTPoison_ by replacing the configuration (environment) value, not by replacing this function. The mocking this continues to work even without a dedicated function.
This also removes the need of having a variable of a different name that would store the HTTP client module and moves the environment initialization to the top of the `main/0` function.
This pull request invalidates https://github.com/Glutexo/onigumo/pull/38.

Remove http_client function

---

test/onigumo_test.exs

So that the order of argument initialization match the left to right order of the arguments in the following asserts. Taken from my [review](https://github.com/Glutexo/onigumo/pull/29#pullrequestreview-870324085) of #29.

Consolidate instruction order in tests

---

config/config.exs
lib/onigumo.ex
test/onigumo_test.exs

An input filename is a configuration value, it does not have to be a module constant. This extraction allows to use this value in tests too.
With this change, I removed the `@testfile_with_urls` attribute from the tests. Its purpose was to expose an otherwise inaccessible value in the `Onigumo` module. With `@input_file` moved to the config, this is no longer necessary, as it’s accessible with `Application.get_env(:onigumo, :input_file)`.
`load_urls/1` takes the filename as an argument and did not have to use the global value even before this change.
Fixes #31.

Move input filename to config

---

test/onigumo_test.exs

DRY the URL input file composition to a new function. This is going to be useful when testing multiple URLs. Also allows to keep only one list of URLs around in the existing tests.

Extract URL input file composition

---

test/onigumo_test.exs

The new function is intended to DRY URL input file composition in tests. Replaced all occurrences of such composition with a call to this function. A follow-up to #44.

Use prepare_input for all URL inputs

---

test/onigumo_test.exs

Instead of vague names like _content_ and _tmp_, used more descriptive ones. The aim is that the variable names describe well enough what their content is, yet still being concise. A follow-up to https://github.com/Glutexo/onigumo/pull/44 based on @nappex’s [review](https://github.com/Glutexo/onigumo/pull/44#issuecomment-1030820723).

Use more explicit names in tests

---

lib/onigumo.ex
test/onigumo_test.exs

Using a static file path as an argument to the function that download more than one URL makes it impossible to generate the file names dynamically. Only kept the file path argument for the final `download/3` function accepting only one URL. Turned the argument of all other functions to a directory path, defaulting to the current working directory.
The new `download/1` function is untested, because there is no way to test it without custom behaviors or the `File` module mocking.

Only pass a dir path to download

---

lib/onigumo.ex
test/onigumo_test.exs

It is not possible to pass a custom input file to the download function and thus the function is not testable. The existing test in fact does not test the file read at all. Fixed by moving the `get_env` call to the main method, which makes a nice symmetry with `http_client`.
Now, the test really tests what it should, the configuration loads are collected to a single place and the functions are even more atomic.
The input path is a string just as a URL and thus these two are indistinguishable. Renamed the function to `download_urls` and `download_url` to avoid this. Still using the ugly guards to distinguish between the URL list and an input file path. Addressing that would be over the scope of this changeset.
Extracted from #67 to make the changeset as small as possible.

Move get input path to main

---

test/onigumo_test.exs

One tests was still manually composing the URL input file without using the extracted function.

Use prepare_input

---

lib/onigumo.ex
test/onigumo_test.exs

As mentioned in https://github.com/Glutexo/onigumo/pull/66#issuecomment-1037506389, enumerable traversal is a trivial concept. It does not make sense to have a separate function just to do `Enum.map`. It brings confusing function dichotomy and a need for guard clauses. Also it discourages from using other types of enumerables like streams.
For the function to be testable, the `get_env` call needed to be moved to `main/0`, which makes nice symmetry with `http_client`. Because the `input_path` parameter is of the same type and thus indistinguishable from a URL, it only makes sense to rename the function.

Remove download_urls/3

---

lib/onigumo.ex
test/onigumo_test.exs

The downloading should work as a stream, everything from picking the URL from the file through the download from the Internet to the local drive file write should happen separately for every item, not by repeated enumeration over a list. ~~This required another version of the `download/3` function accepting a `Stream` and returning a `Stream`.~~ Started with converting the `load_urls/1` function to a `Stream`.

Convert load_urls to a Stream

---

lib/onigumo.ex
test/onigumo_test.exs

A Stream allows to process the URL list without collecting responses to a new in-memory list. Removed thus checking for those responses in tests. They are redundant, because `File.write!/3` always returns `:ok`. On failure, it raises an exception.
Complement to #66.

Convert download_urls_from_file/3 to a Stream

---

lib/onigumo.ex
test/onigumo_test.exs

To make the functions as atomic as possible split the `download_url/3` function to smaller chunks. Now, with `Enum.map` used, this is heavily inefficient as it composes a list of all responses in the memory. This can be however resolved by using [Streams](https://hexdocs.pm/elixir/Stream.html). See #66 and #71.
Fixes #19.

Split download_url to get and write

---

lib/onigumo.ex
test/onigumo_test.exs

To not pass the HTTP client all around, reintroduced the `http_client` function that allows to grab the module only where needed. Now there are many functions that don’t even use the HTTP client and only pass it to another function.
Fixes #76.

♻️ Move HTTP client to a function

---

lib/onigumo.ex
test/onigumo_test.exs

There is no practical need to have the URLs input path to be passed to the function as an argument. There is only going to be a single URL input file and the tests too can load the value from the environment.
The directory path still needs to be passed around because the executive code uses the current working directory, whilst the tests use a temporary directory.

♻️ Move get input path to load_urls

---

test/onigumo_test.exs

The function became being used in other places than in `HTTPoison.get!/3` mocks. Used `prepare_` for symmetry with
`prepare_input/1`.
Fixes #75.

♻️ Rename get! to prepare_response

---

lib/onigumo.ex

To better express that the path is a root for Onigumo’s run.

♻️ Rename dir_path to root_path

---

test/onigumo_test.exs

To have the download test shorter and not to use an overly long anonymous function, extracted the faily complex verification of the downloaded URL to a function. This function can be easily put into `Enum.map`.
Extracted from #73.

♻️ Extract download assertion

---

README.md

I find the “URL address” expression too wordy. I picked “address,” but “URL” would be OK too. In English, I’d instead choose the “URL” version.

♻️ Shorten “URL address“ to just “address”

---

README.md

All Mermaid arrows now have two dashes.

🎨 Consolidate flowchart arrow length

---

README.md

The Downloader checks the existence of the files with URLs, not the Operator. Remove the misleading bullet point.
This pull request is a follow-up to #112 based on its review [conversation](https://github.com/Glutexo/onigumo/pull/112#discussion_r924263481).

📝 Remove a step from Operator

---

README.md

Add anchors for better navigation from the Architecture overview to the specific sections.

📝 Add links to Architecture

---

lib/onigumo.ex
lib/onigumo_cli.ex

The concept of a current working directory only applies to the command-line interface. Thus the cwd call belongs to the Onigumo.CLI module, not Onigumo. Moving this outer-world dependency out of the module makes the “main” function testable.
Fixes #119. Unblocks #56.

🏗 Move root_path to CLI

---

.github/workflows/elixir.yml

The rename of the main branch from elixir to master caused our workflow to not fire for pull requests. The cause is that the _on_ configuration explicitly mentions the branch name. https://github.com/Glutexo/onigumo/blob/3d5aa5b1c460befe86c02d25598b82a3150453f0/.github/workflows/elixir.yml#L5
https://github.com/Glutexo/onigumo/blob/3d5aa5b1c460befe86c02d25598b82a3150453f0/.github/workflows/elixir.yml#L7

🔧 Fix GitHub actions for pull requests

---

lib/onigumo.ex
lib/onigumo_cli.ex
test/onigumo_test.exs

The current Onigumo module does the downloading part of the workflow. Other components like the Parser and the Operator become distinct modules. The rename improves semantics and prevents confusion when more modules appear in the codebase.
Fixes #118.

♻️ Rename Onigumo to Onigumo.Downloader

---

test/onigumo_test.exs

The former _Onigumo_ module has a new name _Onigumo.Downloader_. Rename the test module so the identifiers match.

🚚 Rename OnigumoTest to OnigumoDownloaderTest

---

test/onigumo_downloader_test.exs

[_Onigumo.Downloader.download_url_](https://github.com/Glutexo/onigumo/blob/5e80cf8eb6bf0a16ed0e5bc65bc838541ed20018/lib/onigumo_downloader.ex#L19) returns the return value of [_File.write!_](https://github.com/Glutexo/onigumo/blob/5e80cf8eb6bf0a16ed0e5bc65bc838541ed20018/lib/onigumo_downloader.ex#L41), which is always _:ok_. It is redundant to check for this value and only blurs what the test really verifies.

✅ Remove redundant assert

---

.github/workflows/elixir.yml

Because latest Ubundu does not support Erlang ≤ 24.1, which is the latest version supported by the latest Debian.

Use Ubuntu 20.4 instead of latest

---

lib/onigumo_downloader.ex
test/onigumo_downloader_test.exs

The function does not download anything. It only creates a stream designated for downloading URL. This gives a false sense of complementarity to the download_url. The two functions however do very different things. Hence the rename.

♻️ Rename download_urls_from_file

---

.gitignore

- old definition ignore all occurency of onigumo in path
- it is needed to explicitly speficied we want to ignore onigumo in
root path

Fix ignoring the onigumo escript file

---

lib/cli.ex
test/onigumo_cli_test.exs

fix #162 
fix #188 
I'be tried to be really consistent with existing code and make really the smallest diff as possible.
That's the one of reasons why I parse the component as positional arguments.
Nice thing was appeared, the `OptionParser` is not so good in parsing the positional arguments and its main goal is parsing `switches` (resp. `options`).
IMHO it is emphased by warning which you get from elixir, when you do not pass `:switches` or `:strict`, but these are required only for `switches`.
```shell
warning: not passing the :switches or :strict option to OptionParser is deprecate
```

Use OptionParser to parse component

---

lib/cli.ex
test/onigumo_cli_test.exs

The CLI argument doesn’t need to be tightly coupled to the implementation detail of components being Elixir modules. _ArgumentError_ raised by _Module.safe_concat_ was only a symptom of that. Replaced with a mapping of string arguments (component names) to Elixir modules. As a result _MatchError_ is raised when unknown component is passed, instead of a rather cryptic ArgumentError from _Module.safe_concat_.
Fixes #196.

Use Map instead of Module.safe_concat

---

lib/cli.ex
test/onigumo_cli_test.exs

Capitalized component names were only a remnant of camel-cased elixir modules. Now, with component names being separate, there is no need to follow this convention. Lower-case arguments are the easiest way to interact with an application.
Fixes #197.

Change component name to lowercase

---

lib/cli.ex
test/onigumo_cli_test.exs

CLI usage message

---

lib/cli.ex

Use OptionParser.parse

---

mix.lock

To fix mix compile on some machines.
Fixes #209.

⬆️ Bump ssl_verify_fun to 1.1.7

---

lib/cli.ex

Do not rescue MatchErrors in CLI

---

config/dev.exs
config/test.exs
lib/cli.ex
test/onigumo_cli_test.exs
test/test_helper.exs

[Onigumo.Component](https://github.com/Glutexo/onigumo/blob/32ec35a3585e44ba9858513209131a9638105de5/lib/onigumo/component.ex) is a behavior that can be mocked. CLI tests don’t verify behavior of concrete components. Currently, the [Downloader](https://github.com/Glutexo/onigumo/blob/32ec35a3585e44ba9858513209131a9638105de5/lib/onigumo/downloader.ex) is only run to verify the call works. Defined a mock for the Downlader so the CLI tests only verifies its call, not its behavior.
Defined the expect mock to return the passed working directory to test it’s set properly. The assert verifies the call argument.

Mock Onigumo.Downloader in CLI tests

---

test/onigumo_cli_test.exs

`@urls` module variable was only needed for the actual downloader workings. Now it being mocked, the acutual URLs are irrelevant.

Remove unused @urls

---

README.md

The Operator-Downloader-Parser trinity became only a part of the whole architecture. It’s no longer true that Onigumo is composed of only three components. It wasn’t entirely true before either: there was still the idea of a Materializer.
There are two flowcharts now. It’d be possible to call them a single one consisting of two parts, but clarity doesn’t harm.
Follow-up to #237.

Update description to match diagrams

---

lib/cli.ex
test/onigumo_cli_test.exs

Passing an invalid component name prints a friendly help message instead of crashing with a stack trace. This is now consistent with a situation when an invalid switch is passed.
Fixes #189.

Help message on invalid component

---

lib/cli.ex

In the end, I found the `case` clause more expressive. There are three branches:
* Valid input: launch a component
* Invalid input: unknown switch
* Invalid input: wrong argument count
Having other scenarios in the future, there will be multiple shapes of valid input. E.g. the `-h`/`--help` switch would introduce a branch with a sole switch and no arguments.
The `with` clause seems to be more fitting for cases where we need to collect input from multiple sources. That is partially the case here, because we’re fetching from `@components`. Unfortunately however, I don’t see a way to add that as a `case` branch.

Replace with with case

---

.github/workflows/elixir.yml

Some dependencies don’t work with the latest OTP, which is by now [`28.0-rc2`](https://www.erlang.org/news/177). Downgrading to stable 27 fixes `mix deps.get` in the CI pipeline.
See e.g. #260 for a failing pipeline.

Downgrade OTP to 27 in CI

---

lib/cli.ex

`Keyword.get :working_dir` doesn’t check for other switches. In the future, there may be more switches. Some of those switches may be mutually exclusive with a component name. But now, such switches would be ignored.
Imagine a help switch (`-h`/`--help`). This switch is only valid alone like `onigumo -h`. `onigumo -h downloader` or `onigumo --working-dir`. `downloader --help` are not valid. `Keyword.get` only checks for `:working_dir` though; `:help` is ignored.
`Keyword.pop` yields a keyword list of remaining switches. `:working_dir` is the only valid switch for a component. Any remaining switches mean invalid usage.
There is no way to test this: `-C` is the only valid switch. Mocking OptionParse would be an overkill: `-h` will be added soon. Then, this change can be tested.
Manual …

Valid switches with args didn’t fail

---

lib/cli.ex
test/onigumo_cli_test.exs

fix #240 
One would be help message
another perhaps usage message for invalid usage of onifumo
This PR is done above the PR #238, because it is nature continuation of it.
Before merging this to master must be ensured merge of #238 to #242

Split cli messages to case with invalid usage and help message

---

.github/workflows/elixir.yml

20.04 is going to be browned very soon.

Update CI to Ubuntu 24.04

---

.github/workflows/elixir.yml

The `windows-2022` image has [`core.autocrlf`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreautocrlf) set to `true`. This Git configuration replaces line endings to `\r\n`. `mix format`, however, [expects](https://hexdocs.pm/elixir/Code.html#format_string!/2-newlines) `\n`. The check then fails.
Setting `core.autocrlf` to `false` makes Git leave the newlines intact. On `ubuntu-24.01`, the value is false by default. Re-setting it does no harm.
The newline replacement happens during the clone. The setting needs to happen before. It must be global: before the clone, there is no local repository to set it to.
---
Fixes the CI error in #274.

💚 GitHub action matrix

---

.github/workflows/elixir.yml

Multiline strings are marked with `|`, not `-`. Also, moved the comment to the YAML from the bash command.

💚  Fix CI workflow

---

test/onigumo_cli_test.exs

The tests parametrization using `@invalid_switches` can only test a single invalid switch. It is not possible to test for multiple invalid switches. Turned the parametrization list elements into lists. Now when `@invalid_switches` parameterization elements are lists, it is possible to test multiple invalid switches.
Fixes #279.

Test multiple invalid switches
