Glutexo/onigumo

mix.exs

Fix #7 
update configure information about allowed elixir version

Allow compiling on Debian 11

---

lib/onigumo.ex
test/onigumo_test.exs

Add basic test

---

config/config.exs
config/dev.exs
config/test.exs

Elixir allow write functions without parentheses, but we'd like to write its because of education process.

Add parentheses

---

lib/onigumo.ex
lib/onigumo_cli.ex
mix.exs
test/onigumo_test.exs

Elixir provides option `format` included in tool mix.
I format the code with command `mix format`

Format the code

---

lib/onigumo.ex
lib/onigumo_cli.ex
test/onigumo_test.exs

Load urls from file

---

test/onigumo_test.exs

For better readability and to be reused.

Extract mock get! function

---

test/onigumo_test.exs

Extracted function call results to variables. Kept literals only for simple expressions. Swapped the comparison sides order to be more semantic.

Make asserts more consistent and semantic

---

test/onigumo_test.exs

Extract mock HTTP response body to a function

---

lib/onigumo.ex
test/onigumo_test.exs

First step for #23. This would need to update with every merge into [_elixir_](https://github.com/Glutexo/onigumo/tree/elixir).

🎨 Reformat by mix format

---

lib/onigumo.ex
test/onigumo_test.exs

✨ Base64 encode the filename

---

lib/onigumo.ex
test/onigumo_test.exs

Extract file name creation from a URL to a new function. A follow-up to #73.

♻️ Extract file name creation

---

.github/workflows/elixir.yml
lib/hash.ex
lib/onigumo.ex
test/hash_test.exs
test/onigumo_test.exs

Add check formatting to workflow

---

README.md

Replaced the non-breaking space with a regular one, fixing the heading.

✏️ Fix README Markdown

---

README.md

© Turn copyright name into a link

---

README.md

It’s 2022, man!
A step to #98.

© Bump year in copyright

---

README.md

Repeating Onigumo twice at the beginning of the sentences seems unnatural to me. Also, I was not too fond of the first sentence being that short and lonely.
Extracted from #91.

📝 Join the About paragraphs

---

README.md

🌐 Translate About

---

README.md

The original introduction contained this phrasing, and I like it. It admits that there are already many web scrapers, and this project keeps that in mind.
Extracted from #91.

📝 Use “yet another” instead of “a”

---

README.md

I am not sure about the definite articles and the capital letters. However, I feel they are terms (hence the capitals) and represent single concrete entities (hence the article).
Replaces #91.

🌐 Translate Architecture

---

README.md

Described the component cooperation as a “data flow.”

📝 Make the Diagram heading more precise

---

README.md

Translate the Operator subsection of the Architecture section in the README. The translation is literal; not paying attention to the style.
I decided to go for a literal translation, even though it sounds awful, to minimize the number of changes. I plan to clean up the style in follow-up pull requests.

🌐 Translate Operator

---

README.md

The Start is just a virtual step that is neither part of Onigumo nor a Spider. It is a mere entry-point to the Operator that behaves the same way as during runtime.

📝 Make the Start box rounded

---

README.md

The flowchart was very simple, only mentioning the core parts of the workflow. The distinction between the framework and the userspace needs the diagram to be more complex. I resolved that by adding a subgraph showing the parts that require programming.
Fixes #115.

📝 Add Spider tasks to the flowchart

---

README.md

I accidentally made the start point rectangular. It was part of my last patch that changed the component boxes’ shape. I am making the shape of this virtual item round again.

Make the start bubble round again

---

README.md

Parsing is the process. The original raw data becomes “parsed,” but the result is a “structure.”

📝 Swap the word parsed for structured

---

lib/onigumo.ex

I grouped the public functions, so the only private one is separate at the module's end.

♻️ Move create_file_name up

---

README.md

This time I did my best to keep the style natural, not sticking to a literal translation. I still did not change the actual contents, although I noticed some parts I want to amend.
Namely, I’d mention the flow between the components: the Downloader gets the URL from the Operator and feeds the Parser on the other end of the pipe. Also, I’d like to consolidate the contents with the Operator and Parser sections, e.g., consistently mentioning the check for the already processed items.
I picked the word “fetch” to avoid repeatedly using the word “download” and funny phrases like [“the Downloader downloads.”](https://www.youtube.com/watch?v=XK4RMc1TjbM&t=30s)
Moves #103 forward.

🌐 Translate the Downloader section

---

test/onigumo_cli_test.exs

Test cases when CLI raise an error

---

lib/onigumo/component.ex
lib/onigumo/downloader.ex

Introduced a component behavior and implemented it for _Downloader_. This creates a clear interface between the callers, now CLI and a Supervisor in the future, and the actual component modules. Also this makes the Downloader mockable and thus unit-testable without repeating the internal logic of the actual Downloader.
Resolves #198.

Define a component behavior

---

lib/cli.ex

Rename parsed_switches to switches

---

lib/cli.ex
test/onigumo_cli_test.exs

Remove extra line in CLI output

---

mix.exs

Bump elixir version in mix.exs range >= 1.0.0 and < 2.0.0

---

.github/workflows/elixir.yml

Run CI with os matrix
